# Set wallpaper
#feh --bg-fill /home/msoto/Pictures/Backgrounds/bsd-wallpaper-corner.png
#feh --bg-fill /home/msoto/Pictures/Backgrounds/wp1878733.jpg
#feh --bg-fill /home/msoto/Pictures/Backgrounds/y2k-1.jpg

# FreeBSD
#xsetroot -fg \#de3163 -bg \#6695f7 -bitmap /usr/X11R6/include/X11/bitmaps/cross_weave
# Linux
#xsetroot  -fg rgb:55/40/55 -bg rgb:70/50/70 -bitmap /usr/include/X11/bitmaps/cross_weave


# Load resources
# FreeBSD
#/usr/X11R6/bin/xrdb -merge /home/msoto/.Xresources
/usr/bin/xrdb -merge /home/msoto/.Xresources

# Tap to click synaptics
#synclient TapButton1=1 &

# Keyboard switch caps/escape
#setxkbmap -option caps:swapescape latam &
setxkbmap -option caps:swapescape &

# Compositor
#/usr/X11R6/bin/xcompmgr &

# Start status bar
#/usr/local/bin/dwmblocks &
#/usr/local/bin/st -T 'ststatus' -e /home/msoto/status.sh -g 36x9+20+20

# Load environment
#. $HOME/.profile


# Synaptics
# Enable one-finger tap and double tap
synclient TapButton1=1

# Enable two-finger tap to open right-click menu
synclient TapButton2=3

# Enable horizontal scroll with two fingers
synclient HorizTwoFingerScroll=1

# Enable natural scrolling
synclient VertScrollDelta=-"$(synclient | grep VertScrollDelta | cut -d '=' -f 2 | cut -c 2-)"
synclient HorizScrollDelta=-"$(synclient | grep HorizScrollDelta | cut -d '=' -f 2 | cut -c 2-)"

# wmix fix
/home/msoto/bin/start_wmix.sh &

#################################
#      Start window manager     #
#################################
#
# FVWM* 
#exec /usr/local/bin/fvwm3
#exec /usr/local/bin/fvwm
#exec /usr/local/bin/fvwm2
#exec /usr/local/bin/fvwm
exec /usr//bin/fvwm
#
# DWM
#exec /usr/local/bin/dwm
#
# ICEWM3
#exec /usr/bin/icewm
