. /etc/ksh.kshrc
export LANG=en_US.ISO8859-1
export PS1='$(echo -e "\033[36m.---\033[32m") $PWD 
$(echo -e "\033[36m|_\033[33m\$: \033[00m")'

# Manpath
#export MANPATH="/usr/share/man:/usr/local/share/man:$MANPATH"

# Set shell to vi mode
set -o vi

# Aliases
. ~/.aliases
. ~/.private_aliases
