#!/bin/sh
#xconsole -geometry 480x130-0-0 -daemon -notify -verbose -fn fixed -exitOnFail

# Background
# Bitmap
#/usr/local/bin/xsetroot -bitmap /usr/local/include/X11/bitmaps/grid4
# Solid color
#/usr/local/bin/xsetroot -solid grey
# Image
# FreeBSD
#feh --bg-scale /usr/local/share/pixmaps/palm_trees.jpg
# Linux
feh --bg-scale /usr/include/X11/pixmaps/palm_trees.jpg
