#!/bin/sh
#xconsole -geometry 480x130-0-0 -daemon -notify -verbose -fn fixed -exitOnFail

# Background
# Bitmap
#/usr/local/bin/xsetroot -bitmap /usr/local/include/X11/bitmaps/grid4
#/bin/xsetroot  -fg rgb:55/40/55 -bg rgb:70/50/70 -bitmap /usr/include/X11/bitmaps/cross_weave
xsetroot -fg \#7EA8BE -bg \#C09187 -bitmap /usr/include/X11/bitmaps/escherknot
# Solid color
#/usr/local/bin/xsetroot -solid grey
# Image
# FreeBSD
#feh --bg-scale /usr/local/share/pixmaps/palm_trees.jpg
# Linux
#feh --bg-scale /usr/include/X11/pixmaps/palm_trees.jpg
